version: '3'
services:

  kloyster:
    container_name: kloyster
    image: kloyster
    build:
      context: .
    networks:
      - kloyster
      - caddywork
    external_links:
      - kloyster_redis:redis
    volumes:
      - ./webs/:/app/webs

  redis:
    container_name: kloyster_redis
    image: redis
    volumes:
      - ./db:/data
    networks:
      - kloyster
    command: redis-server --appendonly yes

networks:
  kloyster:
    driver: bridge
