version: '3'
services:

  cloyster:
    container_name: cloyster
    image: cloyster
    build:
      context: .
    networks:
      - cloyster
      - caddywork
    external_links:
      - cloyster_redis:redis
    volumes:
      - ./webs/:/app/webs

  redis:
    container_name: cloyster_redis
    image: redis
    volumes:
      - ./db:/data
    networks:
      - cloyster
    command: redis-server --appendonly yes

networks:
  cloyster:
    driver: bridge
